import { StyleSheet } from
    'react-native';
import { Border, Color, FontFamily, FontSize } from "../GlobalStyles";
export default StyleSheet.create({
    billLayout: {
        height: 92,
        top: 0,
    },
    transfer1FlexBox: {
        textAlign: "center",
        left: 0,
    },
    iconLayout2: {
        height: 89,
        position: "absolute",
    },
    transferLayout: {
        width: 87,
        position: "absolute",
    },
    iconPosition2: {
        left: -1,
        top: -7,
        width: 89,
    },
    paymentLayout: {
        width: 81,
        position: "absolute",
    },
    cardlessPosition: {
        top: 132,
        width: 87,
        height: 92,
        position: "absolute",
    },
    iconLayout1: {
        height: 91,
        position: "absolute",
    },
    groupLayout2: {
        height: 59,
        position: "absolute",
    },
    groupPosition: {
        borderRadius: Border.br_mini,
        left: 0,
        top: 0,
    },
    parentPosition: {
        left: 74,
        position: "absolute",
    },
    idrFlexBox: {
        textAlign: "left",
        color: Color.colorDarkslategray,
    },
    idrTypo: {
        fontFamily: FontFamily.interBold,
        fontWeight: "700",
        fontSize: FontSize.size_mini,
    },
    eyeIconLayout: {
        height: 12,
        width: 16,
        left: 0,
        position: "absolute",
    },
    path79IconLayout: {
        width: 9,
        left: 334,
        height: 16,
        position: "absolute",
    },
    idr3373000Position: {
        top: 13,
        position: "absolute",
    },
    hiClr: {
        color: Color.colorWhite,
        textAlign: "left",
        position: "absolute",
    },
    groupLayout1: {
        height: 33,
        width: 100,
        position: "absolute",
    },
    redeemTypo: {
        fontSize: FontSize.size_sm,
        color: Color.colorWhite,
        textAlign: "left",
        position: "absolute",
    },
    iconPosition1: {
        width: 14,
        top: 0,
        position: "absolute",
    },
    iconLayout: {
        height: 150,
        width: 330,
        top: 34,
        position: "absolute",
    },
    groupLayout: {
        height: 3,
        position: "absolute",
    },
    groupChildLayout: {
        height: 1,
        width: 7,
        backgroundColor: Color.colorDarkgray,
        borderRadius: Border.br_12xs,
        top: 1,
    },
    groupChild3Position: {
        left: 26,
        position: "absolute",
    },
    idr13373000Position: {
        top: 16,
        position: "absolute",
    },
    navLayout: {
        height: 36,
        position: "absolute",
    },
    iconPosition: {
        width: 17,
        top: 0,
        position: "absolute",
    },
    inboxLayout: {
        width: 65,
        position: "absolute",
    },
    settingPosition: {
        width: 69,
        left: 0,
        position: "absolute",
    },
    manajemenKeuangan: {
        color: Color.colorSteelblue_100,
        fontSize: FontSize.size_mini,
        top: 79,
        textAlign: "center",
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        width: 89,
        position: "absolute",
    },
    manajemenKeuanganIcon: {
        top: -7,
        height: 89,
        width: 89,
        left: 0,
    },
    finance: {
        width: 89,
        position: "absolute",
        left: 0,
    },
    moreIcon: {
        left: 278,
        width: 85,
        height: 85,
        top: 131,
        position: "absolute",
    },
    transfer1: {
        textAlign: "center",
        left: 0,
        color: Color.colorSteelblue_100,
        fontSize: FontSize.size_mini,
        top: 79,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
    },
    transferIcon: {
        height: 89,
        position: "absolute",
    },
    transfer: {
        left: 93,
        height: 92,
        top: 0,
    },
    bill: {
        left: 185,
        height: 92,
        top: 0,
    },
    pembelian: {
        textAlign: "center",
        left: 0,
        color: Color.colorSteelblue_100,
        fontSize: FontSize.size_mini,
        top: 79,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
    },
    pembelianIcon: {
        left: -4,
        top: -7,
        height: 89,
        width: 89,
    },
    payment: {
        left: 280,
        height: 92,
        top: 0,
    },
    cardlessIcon: {
        left: -1,
        top: -7,
        width: 89,
    },
    cardless: {
        left: 1,
    },
    openAccount: {
        left: 93,
    },
    deposito: {
        left: 185,
    },
    menu: {
        top: 370,
        left: 13,
        width: 361,
        height: 224,
        position: "absolute",
    },
    groupChild: {
        backgroundColor: Color.colorGoldenrod,
        height: 59,
        position: "absolute",
        width: 358,
    },
    groupItem: {
        width: 318,
        height: 59,
        position: "absolute",
        backgroundColor: "transparent",
    },
    tabunganTandamata: {
        fontSize: FontSize.size_smi,
        color: Color.colorDarkslategray,
        top: 1,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        left: 0,
        position: "absolute",
    },
    text: {
        left: 123,
        fontSize: 11,
        fontFamily: FontFamily.interMedium,
        fontWeight: "500",
        color: Color.colorDarkslategray,
        top: 0,
        position: "absolute",
    },
    idr13373000: {
        left: 22,
        top: 16,
        position: "absolute",
        textAlign: "left",
        color: Color.colorDarkslategray,
    },
    eyeSlashIcon: {
        top: 20,
    },
    tabunganTandamataParent: {
        top: 12,
        width: 205,
        height: 34,
    },
    path79Icon: {
        height: 16,
        top: 23,
    },
    maskGroup27: {
        width: 30,
        height: 35,
        left: 24,
    },
    rectangleParent: {
        top: 209,
        width: 358,
        height: 59,
        shadowOpacity: 1,
        elevation: 10,
        shadowRadius: 10,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowColor: "rgba(0, 0, 0, 0.02)",
        left: 16,
    },
    bgHeadIcon: {
        width: 413,
        height: 214,
        left: 0,
        top: 0,
        position: "absolute",
    },
    tammi: {
        left: 18,
        fontSize: 26,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        top: 0,
    },
    hi: {
        top: 5,
        fontSize: 18,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        left: 0,
    },
    tammiParent: {
        top: 137,
        width: 84,
        height: 22,
        left: 16,
        position: "absolute",
    },
    poin: {
        top: 139,
        left: 186,
        fontFamily: FontFamily.interBold,
        fontWeight: "700",
        fontSize: FontSize.size_mini,
    },
    groupInner: {
        backgroundColor: Color.colorWhite,
        opacity: 0.52,
        borderRadius: Border.br_mini,
        left: 0,
        top: 0,
    },
    swapHorizontalIcon: {
        top: 3,
        height: 14,
        width: 16,
        left: 0,
        position: "absolute",
    },
    redeem: {
        fontFamily: FontFamily.interRegular,
        left: 22,
        top: 0,
    },
    swapHorizontalParent: {
        top: 6,
        left: 12,
        width: 77,
        height: 17,
        position: "absolute",
    },
    rectangleGroup: {
        left: 273,
        top: 131,
    },
    frameChild: {
        top: 52,
        left: 10,
        width: 367,
        height: 44,
        position: "absolute",
    },
    bgHeadParent: {
        height: 201,
        left: 0,
        top: 0,
        position: "absolute",
        overflow: "hidden",
        width: 390,
    },
    userProfileIcon: {
        height: 13,
        left: 0,
    },
    myInfo: {
        left: 21,
        top: 1,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
    },
    userProfileParent: {
        top: 114,
        width: 62,
        height: 13,
        left: 16,
        position: "absolute",
    },
    digicash: {
        fontSize: 12,
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        left: 0,
        top: 0,
        position: "absolute",
    },
    idr3373000: {
        fontFamily: FontFamily.interBold,
        fontWeight: "700",
        fontSize: FontSize.size_mini,
        left: 22,
        textAlign: "left",
        color: Color.colorDarkslategray,
    },
    eyeSlashIcon1: {
        top: 17,
    },
    digicashParent: {
        top: 15,
        width: 128,
        height: 31,
    },
    path79Icon1: {
        top: 22,
        height: 16,
    },
    image39Icon: {
        top: 10,
        left: 20,
        width: 38,
        height: 38,
        position: "absolute",
    },
    rectangleContainer: {
        top: 282,
        width: 358,
        height: 59,
        shadowOpacity: 1,
        elevation: 10,
        shadowRadius: 10,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowColor: "rgba(0, 0, 0, 0.02)",
        left: 16,
    },
    infoDanPromo: {
        fontSize: 16,
        letterSpacing: -0.2,
        fontWeight: "600",
        fontFamily: FontFamily.interSemiBold,
        color: "#000",
        top: 0,
        position: "absolute",
    },
    bannerIcon: {
        left: 0,
    },
    banner1Icon: {
        left: 340,
    },
    groupChild1: {
        left: 15,
        position: "absolute",
    },
    groupChild2: {
        borderRadius: 3,
        backgroundColor: "#2586b0",
        width: 11,
        left: 0,
        top: 0,
    },
    groupChild3: {
        height: 1,
        width: 7,
        backgroundColor: Color.colorDarkgray,
        borderRadius: Border.br_12xs,
        top: 1,
    },
    groupView: {
        top: 193,
        left: 163,
        width: 33,
    },
    infoDanPromoParent: {
        top: -29,
        width: 670,
        height: 196,
        left: 0,
        position: "absolute",
    },
    homeAlternative2Inner: {
        top: 616,
        left: 17,
        width: 373,
        height: 167,
        position: "absolute",
        overflow: "hidden",
    },
    path3655Icon: {
        height: 103,
        left: 0,
        width: 390,
    },
    qrisIcon: {
        left: 149,
        width: 91,
        top: 0,
    },
    mailOutlineIcon: {
        left: 25,
        height: 13,
    },
    inbox: {
        color: Color.colorSlategray,
        fontSize: FontSize.size_smi,
        textAlign: "center",
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        top: 25,
        width: 65,
        left: 0,
    },
    favorite: {
        left: 69,
        color: Color.colorSlategray,
        fontSize: FontSize.size_smi,
        textAlign: "center",
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        top: 25,
        width: 65,
    },
    iconFeatherHeart: {
        left: 94,
        height: 15,
    },
    left: {
        width: 134,
        left: 0,
        top: 0,
    },
    setting1: {
        top: 24,
        color: Color.colorSlategray,
        fontSize: FontSize.size_smi,
        textAlign: "center",
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
    },
    iconFeatherSettings: {
        height: 16,
        width: 16,
        top: 0,
    },
    setting: {
        height: 35,
        top: 0,
    },
    logOut: {
        color: Color.colorSlategray,
        fontSize: FontSize.size_smi,
        textAlign: "center",
        fontFamily: FontFamily.antipastoPro,
        fontWeight: "500",
        top: 23,
        left: 0,
    },
    iconFeatherLogOut: {
        height: 14,
        left: 24,
    },
    logout: {
        left: 72,
        top: 1,
        height: 34,
    },
    right: {
        left: 222,
        width: 137,
        height: 35,
        top: 1,
        position: "absolute",
    },
    nav: {
        top: 69,
        width: 359,
        left: 16,
    },
    navigation: {
        top: 797,
        flex:1,
        height: 119,
        left: 0,
        position: "absolute",
        width: 390,
    },
    topBarIcon: {
        width: 393,
        height: 46,
        left: 0,
        top: 0,
        position: "absolute",
        overflow: "hidden",
    },
    homeAlternative2: {
        height: 916,
        backgroundColor: "transparent",
        overflow: "hidden",
        width: 390,
    },
    backgroundImage: {
        flex: 1,
        resizeMode: 'cover', // or 'stretch' or 'contain'
        justifyContent: 'center',
    },
    card: {
        backgroundColor: "#fff",
        // borderWidth:1,
        borderRadius: 10,
        borderEndEndRadius: 10,
        marginTop: 10,
        marginLeft: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 8.00,
        elevation: 10,
        marginRight: 20,
        // marginBottom: 10,
        // paddingTop: 10,
        // paddingBottom: 10,
        height:50,
        flex:1,
        flexDirection:'row'
    },
    card2: {
        backgroundColor: "#fff",
        // borderWidth:1,
        borderRadius: 10,
        borderEndEndRadius: 10,
        marginTop: 10,
        marginLeft: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 8.00,
        elevation: 10,
        marginRight: 20,
        // marginBottom: 10,
        // paddingTop: 10,
        // paddingBottom: 10,
        height: 80,
        flex: 1,
        flexDirection: 'row'
    }
})